config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
]

rooms/models.py
from django.db import models  # 1.장고 관련 된것을 모두 임포트
from core import models as core_models  # 2. 서드파티 패키지 임포트
from django.urls import reverse
from django_countries.fields import CountryField  # 3. 그다음 내가 만든것 임포트
from users import models as user_models


class AbstractItem(core_models.TimeStampedModel):
    """ Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Model """

    class Meta:
        verbose_name_plural = "Room Type"


class Amenity(AbstractItem):
    """ Amenity Model """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """ Facility Model """

    class Meta:
        verbose_name_plural = "Facilites"


class HouseRule(AbstractItem):
    """ House Rule Model """

    class Meta:
        verbose_name_plural = "House Rule"


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_phptos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """ Room Models """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)

    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()

    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    # 다른 모델과 연결. Foreignkey
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )

    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenity = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facility = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) != 0:  # 그 방에 리뷰가 없는경우는? 0으로 나누게 되는데?
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

rooms/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage
from django_countries import countries
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.http import Http404
from . import models


class HomeView(ListView):
    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    page_kwarg = "page"


class RoomDetail(DetailView):
    model = models.Room
    pk_url_kwarg = "pk"


def room_detail(request, pk):
    try:
        room = models.Room.objects.get(pk=pk)
        return render(request, "rooms/detail.html", context={"room": room})
    except models.Room.DoesNotExist:
        raise Http404()
        # return redirect(reverse("core:home"))


def all_rooms(request):

    page = request.GET.get("page", 1)
    room_list = models.Room.objects.all()
    paginator = Paginator(room_list, 10, orphans=5)
    try:
        rooms = paginator.page(int(page))
        return render(request, "rooms/home.html", {"page": rooms})
    except EmptyPage:
        return redirect("/")
    except ValueError:
        return redirect("/")
    except Exception:
        return redirect("/")


def search(request):
    print(vars(request.GET))
    city = request.GET.get("city", "Anywhere")
    city = str.capitalize(city)
    room_types = models.RoomType.objects.all()
    return render(
        request,
        "rooms/search.html",
        {"city": city, "countries": countries, "room_types": room_types},
    )

templates/rooms/detail.html
{% extends "base.html" %} 

{% block page_name %} Detail {% endblock page_name %}
{% block content %}
  <div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
  </div>
  <div>
    <h2>
      By: {{room.host.username}}
      {% if room.host.superhost %} (superhost) 
      {% endif %}
    </h2>

    <h3>Amenities</h3>
    <ul>
      {% for a in room.amenity.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>
    
    <h3>Facilities</h3>
    <ul>
      {% for a in room.facility.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>

    <h3>House Rules</h3>
    <ul>
      {% for a in room.house_rules.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>
    
  </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %} 

{% block page_title %} Detail {% endblock page_title %}
{% block content %}
  <div>
    <h1>{{object.name}}</h1>
    <h3>{{room.description}}</h3>
  </div>
  <div>
    <h2>
      By: {{room.host.username}}
      {% if room.host.superhost %} (superhost) 
      {% endif %}
    </h2>

    <h3>Amenities</h3>
    <ul>
      {% for a in room.amenity.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>
    
    <h3>Facilities</h3>
    <ul>
      {% for a in room.facility.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>

    <h3>House Rules</h3>
    <ul>
      {% for a in room.house_rules.all %}
      <li>{{a}}</li>
      {% endfor %}
    </ul>
    
  </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
  Home
{% endblock page_title %}

{% block content %}

  {% for room in object_list  %}
    <a href ="{% url "rooms:detail" room.pk %}"> <h4> {{room.name }} / {{room.price}} </h4> </a>
  {% endfor %}


  {% if page_obj.has_previous %}
    <a href="?page={{page_obj.number|add:-1}}">Previous</a>
  {% endif %}

  Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

  {% if page_obj.has_next  %}
      <a href="?page={{page_obj.number|add:1}}">Next</a>
  {% endif %}

{% endblock content %}

  

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block content %}
    <h2> Search!! </h2>
{% block search-bar %}
{% endblock search-bar %}
    <h4> Searching by {{city}} </h4>
    <form method = "get" action = "{% url "rooms:search" %}">
        <div>
            <label for="city">City</label>
            <input value= "{{city}}" id = "city" name="city" placeholder = "Search By City"/> 
        </div>
        <div>
            <label for="country">Country</label>
            <select id="country" name="country" >
                {% for country in countries  %}
                    <option value="{{country.code}}">{{country.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="room_type">Room Type</label>
            <select id="room_type" name="room_type" >
                {% for room_type in room_types  %}
                    <option value="{{room_type.pk}}">{{room_type.name}}</option>
                {% endfor %}
            </select>
        </div>
        <button>Search</button>
    </form>
{% endblock content %}